// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"go-test/study_wire/service"
)

// Injectors from wire.go:

func InitializeBar() *service.Bar {
	foo := service.NewFoo()
	bar := service.NewBar(foo)
	return bar
}
